spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/fornecedor
    username: root
    password: mariadb

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: false
